name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Clean Project
      - name: Clean Project
        run: ./gradlew clean --stacktrace

      - name: Run Test
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

      - name: Stage Build Assemble
        run: ./gradlew assembleStage

